version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      next-and-react:
        patterns: ["next", "react", "react-dom", "eslint-config-next"]
      development-tools:
        dependency-type: development
